name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: ros:jazzy
    steps:
      - uses: actions/checkout@v4

      - name: rosdep update
        run: rosdep update

      - name: rosdep install
        run: rosdep install --from-paths src -y --ignore-src

      - name: colcon build
        run: colcon build --symlink-install

      - name: colcon test
        run: colcon test

      - name: colcon test-result
        run: colcon test-result --verbose
